database_url: ${remote_url:localhost:3306}

spring:
  datasource:
    url: jdbc:mysql://${database_url}/art_prod
    username: art_prod_user
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
